# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mDAN' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for mDAN
	pod 'DeclarationAccessibility', :git => "https://gitlab.tech.orange/tayeb.sedraia/accessibility_ios_accessibility_statement.git"


end
